// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function screenId(screenId$1) {
  switch (screenId$1) {
    case 0 : 
        return "screen.drawer";
    case 1 : 
        return "screen.welcome";
    case 2 : 
        return "screen.modal";
    case 3 : 
        return "screen.lightbox";
    case 4 : 
        return "screen.about";
    
  }
}

exports.screenId = screenId;
/* No side effect */
