// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactNavigation = require("react-navigation");

function create(routeConfig, drawerNavigatorConfig) {
  return ReactNavigation.createDrawerNavigator(routeConfig, drawerNavigatorConfig);
}

exports.create = create;
/* react-navigation Not a pure module */
