// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactNavigation = require("react-navigation");

function create(routeConfig, stackNavigatorConfig) {
  return ReactNavigation.createStackNavigator(routeConfig, stackNavigatorConfig);
}

exports.create = create;
/* react-navigation Not a pure module */
