// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Welcome$RnPlayground = require("../screens/Welcome.js");
var StackNavigator$RnPlayground = require("../types/StackNavigator.js");
var DrawerNavigator$RnPlayground = require("../types/DrawerNavigator.js");

var drawerConfig = {
  welcome: {
    screen: Welcome$RnPlayground.jsComponent
  }
};

var drawerNavigatorConfig = {
  initialRouteName: "welcome",
  contentOptions: {
    activeTintColor: "#e91e63"
  }
};

var drawer = DrawerNavigator$RnPlayground.create(drawerConfig, drawerNavigatorConfig);

var routeConfig = {
  drawer: {
    screen: drawer
  }
};

var stackNavigatorConfig = {
  initialRouteName: "drawer",
  headerMode: "none"
};

var component = StackNavigator$RnPlayground.create(routeConfig, stackNavigatorConfig);

exports.drawerConfig = drawerConfig;
exports.drawerNavigatorConfig = drawerNavigatorConfig;
exports.drawer = drawer;
exports.routeConfig = routeConfig;
exports.stackNavigatorConfig = stackNavigatorConfig;
exports.component = component;
/* drawer Not a pure module */
