// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Font$BsExpo = require("bs-expo/lib/js/src/font.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Image$BsReactNative = require("bs-react-native/lib/js/src/components/image.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Container$BsNativeBase = require("bs-native-base/lib/js/src/components/Container.js");
var StatusBar$BsReactNative = require("bs-react-native/lib/js/src/components/statusBar.js");
var StyleSheet$BsReactNative = require("bs-react-native/lib/js/src/styleSheet.js");
var StyleProvider$BsNativeBase = require("bs-native-base/lib/js/src/components/StyleProvider.js");
var ImageBackground$BsReactNative = require("bs-react-native/lib/js/src/components/imageBackground.js");

var styles = StyleSheet$BsReactNative.create({
      imageContainer: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* [] */0
          ]),
      logoContainer: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.flex(1),
            /* :: */[
              Style$BsReactNative.marginTop(/* Pt */Block.__(0, [20])),
              /* [] */0
            ]
          ]),
      logo: Style$BsReactNative.style(/* :: */[
            Style$BsReactNative.width(/* Pt */Block.__(0, [280])),
            /* :: */[
              Style$BsReactNative.height(/* Pt */Block.__(0, [100])),
              /* :: */[
                Style$BsReactNative.position(/* Absolute */0),
                /* :: */[
                  Style$BsReactNative.left(/* Pt */Block.__(0, [40])),
                  /* :: */[
                    Style$BsReactNative.top(/* Pt */Block.__(0, [35])),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ])
    });

var component = ReasonReact.reducerComponent("Welcome");

var fontsPromise = Font$BsExpo.loadAll(/* :: */[
      /* tuple */[
        "Roboto",
        require("native-base/Fonts/Roboto.ttf")
      ],
      /* :: */[
        /* tuple */[
          "Roboto_medium",
          require("native-base/Fonts/Roboto_medium.ttf")
        ],
        /* :: */[
          /* tuple */[
            "Ionicons",
            require("@expo/vector-icons/fonts/Ionicons.ttf")
          ],
          /* [] */0
        ]
      ]
    ]);

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              fontsPromise.then((function () {
                        Curry._1(self[/* send */3], /* SetReady */0);
                        return Promise.resolve(/* () */0);
                      })).catch((function (err) {
                      console.log("Error!", err);
                      return Promise.resolve(/* () */0);
                    }));
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              if (self[/* state */1][/* ready */0]) {
                return ReasonReact.element(/* None */0, /* None */0, StyleProvider$BsNativeBase.make(/* None */0, /* array */[ReasonReact.element(/* None */0, /* None */0, Container$BsNativeBase.make(/* Some */[styles.imageContainer], /* array */[
                                          ReasonReact.element(/* None */0, /* None */0, StatusBar$BsReactNative.make(/* None */0, /* Some */[/* lightContent */-106329341], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                                          ReasonReact.element(/* None */0, /* None */0, ImageBackground$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* Required */Block.__(1, [require("../../../../assets/launchscreen-bg.png")])], /* Some */[styles.imageContainer], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                                          ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles.logoContainer], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Image$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* Required */Block.__(1, [require("../../../../assets/logo-kitchen-sink.png")])], /* Some */[styles.logo], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[]))]))
                                        ]))]));
              } else {
                return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Text$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */["LOADING!!!"]))]));
              }
            }),
          /* initialState */(function () {
              return /* record */[/* ready */false];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, _$1) {
              return /* Update */Block.__(0, [/* record */[/* ready */true]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function () {
        return make(/* array */[]);
      }));

exports.styles = styles;
exports.component = component;
exports.fontsPromise = fontsPromise;
exports.make = make;
exports.jsComponent = jsComponent;
/* styles Not a pure module */
