// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var NativeBase = require("native-base");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Props$BsNativeBase = require("../private/props.js");

function make(style, block, primary, transparent, success, danger, warning, info, bordered, disabled, rounded, large, small, active, children) {
  return ReasonReact.wrapJsForReason(NativeBase.Button, Props$BsNativeBase.extendTouchableOpacity(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, {
                  style: Js_undefined.fromOption(style),
                  block: Js_undefined.fromOption(block),
                  primary: Js_undefined.fromOption(primary),
                  transparent: Js_undefined.fromOption(transparent),
                  success: Js_undefined.fromOption(success),
                  danger: Js_undefined.fromOption(danger),
                  warning: Js_undefined.fromOption(warning),
                  info: Js_undefined.fromOption(info),
                  bordered: Js_undefined.fromOption(bordered),
                  disabled: Js_undefined.fromOption(disabled),
                  rounded: Js_undefined.fromOption(rounded),
                  large: Js_undefined.fromOption(large),
                  small: Js_undefined.fromOption(small),
                  active: Js_undefined.fromOption(active)
                }), children);
}

exports.make = make;
/* ReasonReact Not a pure module */
