// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var NativeBase = require("native-base");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(style, padder, disableKBDismissScroll, enableResetScrollToCoords, keyboardShouldPersistTaps, children) {
  return ReasonReact.wrapJsForReason(NativeBase.Content, {
              style: Js_undefined.fromOption(style),
              padder: Js_undefined.fromOption(padder),
              disableKBDismissScroll: Js_undefined.fromOption(disableKBDismissScroll),
              enableResetScrollToCoords: Js_undefined.fromOption(enableResetScrollToCoords),
              keyboardShouldPersistTaps: Js_undefined.fromOption(keyboardShouldPersistTaps)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
