// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var NativeBase = require("native-base");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(drawerType, content, onClose, onCloseStart, onOpen, onOpenStart, tapToClose, drawerOpen, children) {
  var tmp;
  if (drawerType) {
    switch (drawerType[0]) {
      case 0 : 
          tmp = "displace";
          break;
      case 1 : 
          tmp = "overlay";
          break;
      case 2 : 
          tmp = "static";
          break;
      
    }
  } else {
    tmp = "";
  }
  return ReasonReact.wrapJsForReason(NativeBase.Drawer, {
              type: tmp,
              content: Js_undefined.fromOption(content),
              onClose: Js_undefined.fromOption(onClose),
              onCloseStart: Js_undefined.fromOption(onCloseStart),
              onOpen: Js_undefined.fromOption(onOpen),
              onOpenStart: Js_undefined.fromOption(onOpenStart),
              tapToClose: Js_undefined.fromOption(tapToClose),
              open: Js_undefined.fromOption(drawerOpen)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
