// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var NativeBase = require("native-base");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Props$BsNativeBase = require("../private/props.js");

function make(style, searchBar, rounded, children) {
  return ReasonReact.wrapJsForReason(NativeBase.Header, Props$BsNativeBase.extendView(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, {
                  style: Js_undefined.fromOption(style),
                  searchBar: Js_undefined.fromOption(searchBar),
                  rounded: Js_undefined.fromOption(rounded)
                }), children);
}

exports.make = make;
/* ReasonReact Not a pure module */
