// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var NativeBase = require("native-base");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var Props$BsNativeBase = require("../private/props.js");

function make(style, searchBar, rounded) {
  var partial_arg = Props$BsNativeBase.extendView(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, {
        style: Js_undefined.fromOption(style),
        searchBar: searchBar,
        rounded: rounded
      });
  var partial_arg$1 = NativeBase.Header;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
