// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var NativeBase = require("native-base");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(style, iconType, name, ios, android, active, children) {
  var tmp;
  if (iconType) {
    switch (iconType[0]) {
      case 0 : 
          tmp = "Entypo";
          break;
      case 1 : 
          tmp = "EvilIcons";
          break;
      case 2 : 
          tmp = "Feather";
          break;
      case 3 : 
          tmp = "FontAwesome";
          break;
      case 4 : 
          tmp = "Foundation";
          break;
      case 5 : 
          tmp = "Ionicons";
          break;
      case 6 : 
          tmp = "MaterialCommunityIcons";
          break;
      case 7 : 
          tmp = "MaterialIcons";
          break;
      case 8 : 
          tmp = "Octicons";
          break;
      case 9 : 
          tmp = "SimpleLineIcons";
          break;
      case 10 : 
          tmp = "Zocial";
          break;
      
    }
  } else {
    tmp = "";
  }
  return ReasonReact.wrapJsForReason(NativeBase.Icon, {
              style: Js_undefined.fromOption(style),
              type: tmp,
              name: Js_undefined.fromOption(name),
              ios: Js_undefined.fromOption(ios),
              android: Js_undefined.fromOption(android),
              active: Js_undefined.fromOption(active)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
