// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var NativeBase = require("native-base");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function make(style, selectable, accessible, ellipsizeMode, nativeID, numberOfLines, onLayout, onLongPress, onPress, pressRetentionOffset, allowFontScaling, testID, disabled, selectionColor, textBreakStrategy, adjustsFontSizeToFit, minimumFontScale, suppressHighlighting, children) {
  return ReasonReact.wrapJsForReason(NativeBase.Title, {
              style: Js_undefined.fromOption(style),
              selectable: Js_undefined.fromOption(selectable),
              accessible: Js_undefined.fromOption(accessible),
              ellipsizeMode: Js_undefined.fromOption(ellipsizeMode),
              nativeID: Js_undefined.fromOption(nativeID),
              numberOfLines: Js_undefined.fromOption(numberOfLines),
              onLayout: Js_undefined.fromOption(onLayout),
              onLongPress: Js_undefined.fromOption(onLongPress),
              onPress: Js_undefined.fromOption(onPress),
              pressRetentionOffset: Js_undefined.fromOption(pressRetentionOffset),
              allowFontScaling: Js_undefined.fromOption(allowFontScaling),
              testID: Js_undefined.fromOption(testID),
              disabled: Js_undefined.fromOption(disabled),
              selectionColor: Js_undefined.fromOption(selectionColor),
              textBreakStrategy: Js_undefined.fromOption(textBreakStrategy),
              adjustsFontSizeToFit: Js_undefined.fromOption(adjustsFontSizeToFit),
              minimumFontScale: Js_undefined.fromOption(minimumFontScale),
              suppressHighlighting: Js_undefined.fromOption(suppressHighlighting)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
